### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by iJaniashvili** [nodejs/nodejs-ka#3]
ჯგუფის წევრებმა პაროლებისთვის მიწერეთ

@irakli-janiashvili (email: irakli.janiashvili@gmail.com / twitter: [@iJaniashvili](http://twitter.com/iJaniashvili))
- Twitter: https://twitter.com/iojs_ka
- Email: iojs.georgia@gmail.com

@Stichoza (email: me@stichoza.com / twitter: [@Stichoza](https://twitter.com/Stichoza))
- Medium: https://medium.com/@iojs_ka

**Comment by Stichoza** [comment]
P.S. Medium-ზე Login via Twitter

**Comment by tk120404** [comment]
@iJaniashvili Can you please close this issue
