### ISSUE TITLE
ძირითადი საიტის თარგმნა

### ISSUE THREAD

**Issue by iJaniashvili** [nodejs/nodejs-ka#8]
მგონი დროა დავიწყოთ რას იტყვით

iojs.ge → iojs.org/ka

@Stichoza @davit-khaburdzania @nodar-chkuaselidze

**Comment by irakli-janiashvili** [comment]
ამის მერე დოკუმენტაციაც დასაწყებია..

**Comment by Stichoza** [comment]
მე დავფორკე website რეპო და რო დავიწყე იმდენი ტერმინი შემხვდა რო რავიცი ;დ ქართული ძაან ძველი ენაა რა. ძველი კი არა, არ განახლებულა თამარ მეფის მერე, ხოდა ძნელია.

ნამიოკი: :beers:

**Comment by irakli-janiashvili** [comment]
Roger that, ახალი მეფე გვჭირდება ანუ.

ნამიოკის გიფი: 
![beer](http://p.fod4.com/upload/aff3567c9abaad4b798a350dc1e1b1a3/XTMGjFZTuSj9ypajCGtl_Beer%20Big%20Gulp.gif)

**Comment by irakli-janiashvili** [comment]
გერმანული iojs.org https://iojs.org/de/index.html

**Comment by Stichoza** [comment]
ხვალ სად დავიდროპოთ? ვილსი (Wheels) კაია ჩვენთვის, ლუდი კაი აქვთ და სიწყნარეა პაპსა ჯგუფები არ იმასშვებიან ტვინს
